# Generated by Django 4.2 on 2023-06-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JejuFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("j_name", models.CharField(blank=True, max_length=50, null=True)),
                ("j_latitude", models.FloatField(blank=True, null=True)),
                ("j_longitude", models.FloatField(blank=True, null=True)),
                ("j_theme", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "jeju_facility",
                "managed": False,
            },
        ),
    ]
