# Generated by Django 4.2.2 on 2023-06-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0002_rename_passward_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="registerd_dttm",
            new_name="registered_dttm",
        ),
    ]
