# Generated by Django 4.2.2 on 2023-06-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0003_rename_registerd_dttm_user_registered_dttm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("m_name", models.CharField(max_length=100)),
                ("m_id", models.CharField(max_length=100)),
                ("m_pwd", models.CharField(max_length=100)),
                ("m_email", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "member",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
